# Generated by Django 2.1 on 2018-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile_phone',
            new_name='state',
        ),
    ]
