# Generated by Django 2.1 on 2018-09-04 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0004_auto_20180904_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=999),
            preserve_default=False,
        ),
    ]
