# Generated by Django 2.1 on 2018-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0005_blogcontent_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='intro',
            field=models.TextField(),
        ),
    ]
