# Generated by Django 2.1 on 2018-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0007_shopcategory_shopproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
