# Generated by Django 2.1.1 on 2018-09-07 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0009_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='ordered_times',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
