# Generated by Django 2.1.1 on 2018-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantomapp', '0010_shopproduct_ordered_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='ordered_times',
            field=models.IntegerField(),
        ),
    ]
